version: "2"
services:
  module1:
    build: ./DockerSub1/
    image: kashishhike/dockersub1:latest
    command: dockerize -wait tcp://module2:4010 
    hostname: docker submodule 1
    ports:
      - "4008:80"
    networks:
      - webnet

  module2:
    build: ./DockerSub2/
    image: kashishhike/dockersub2:latest
    hostname: docker submodule 2
    ports:
      - "4010:80"
    networks:
      - webnet

networks:
  webnet:
